// AUTO-GENERATED by scripts/consolidate-tests.js
// Consolidated tests for source: components\pages\ReviewPage

import { describe, it, expect, vi } from 'vitest'
import { mount } from '@vue/test-utils'
import ReviewPage from '/src/components/pages/ReviewPage.vue'
import AnnotationPage from '/src/components/pages/AnnotationPage.vue'
import { test, expect, vi, afterEach } from 'vitest'
import { TMToken, TMTokenBlock } from '/src/components/managers/TokenManager'
import { shallowMount } from '@vue/test-utils'


// from: test\components\ReviewAnnotationPages.spec.ts
(() => {

const emitter = { on: vi.fn(), off: vi.fn(), emit: vi.fn() }

const tokenManager = {
  tokens: [],
  edited: [],
  getBlockByStart: () => null,
}

const store = {
  state: {
    annotationManager: { inputSentences: [{ id: 0, text: 'a' }], annotations: [{ entities: [] }] },
    tokenManager,
    tokenManagers: [tokenManager],
    currentPage: 'annotate',
  },
  commit: vi.fn(),
}

describe('Review and Annotation pages', () => {
  it('mounts ReviewPage and hooks emitter', () => {
    const wrapper = mount(ReviewPage as unknown as Record<string, unknown>, { global: { mocks: { $store: store, emitter }, stubs: { 'labels-block': true, 'token': true, 'aggregate-block': true, 'token-block': true, 'info-bar': true } } })
    expect(wrapper.exists()).toBe(true)
    expect(emitter.on).toHaveBeenCalled()
  })

  it('mounts AnnotationPage and hooks emitter', () => {
    const wrapper = mount(AnnotationPage as unknown as Record<string, unknown>, { global: { mocks: { $store: store, emitter }, stubs: { 'labels-block': true, 'token': true, 'aggregate-block': true, 'token-block': true, 'info-bar': true } } })
    expect(wrapper.exists()).toBe(true)
    expect(emitter.on).toHaveBeenCalled()
  })
})

})();

// from: test\reviewpage.spec.ts
(() => {

afterEach(() => {
  vi.restoreAllMocks()
  // reset global onbeforeunload to avoid leaking between tests
  try { window.onbeforeunload = null } catch (e) {}
})

test('created with non-empty inputSentences registers listeners and tokenizes, beforeUnmount cleans up', () => {
  const addSpy = vi.spyOn(document, 'addEventListener')
  const removeSpy = vi.spyOn(document, 'removeEventListener')

  const emitterOn = vi.fn()
  const emitterOff = vi.fn()

  const fakeThis: any = {
    annotationManager: { inputSentences: [{ id: 1, text: 'x' }] },
    tokenizeCurrentSentence: vi.fn(),
    selectTokens: vi.fn(),
    beforeLeave: vi.fn(),
    emitter: { on: emitterOn, off: emitterOff },
  }

  // Call created hook
  ;(ReviewPage as any).created.call(fakeThis)

  // It should tokenize because there are sentences
  expect(fakeThis.tokenizeCurrentSentence).toHaveBeenCalled()

  // document.addEventListener should have been called for 'mouseup' with a function
  expect(addSpy).toHaveBeenCalledWith('mouseup', expect.any(Function))

  // window.onbeforeunload should be set to beforeLeave handler
  expect(window.onbeforeunload).toBe(fakeThis.beforeLeave)

  // emitter.on should be called for tokenizeCurrentSentence
  expect(emitterOn).toHaveBeenCalledWith('tokenizeCurrentSentence', expect.any(Function))

  // Call the handler that was registered on document to ensure it calls selectTokens
  const handler = addSpy.mock.calls.find(c => c[0] === 'mouseup')![1]
  ;(handler as any)({ type: 'mouseup' })
  expect(fakeThis.selectTokens).toHaveBeenCalledWith({ type: 'mouseup' })

  // Now call beforeUnmount and verify cleanup
  ;(ReviewPage as any).beforeUnmount.call(fakeThis)
  expect(removeSpy).toHaveBeenCalledWith('mouseup', fakeThis.selectTokens)
  expect(emitterOff).toHaveBeenCalledWith('tokenizeCurrentSentence', fakeThis.tokenizeCurrentSentence)
})

test('created with empty inputSentences does not tokenize immediately but still registers listeners', () => {
  const addSpy = vi.spyOn(document, 'addEventListener')
  const emitterOn = vi.fn()

  const fakeThis: any = {
    annotationManager: { inputSentences: [] },
    tokenizeCurrentSentence: vi.fn(),
    selectTokens: vi.fn(),
    beforeLeave: vi.fn(),
    emitter: { on: emitterOn, off: vi.fn() },
  }

  ;(ReviewPage as any).created.call(fakeThis)

  // Should not tokenize because there are no sentences
  expect(fakeThis.tokenizeCurrentSentence).not.toHaveBeenCalled()

  // Should still register mouseup listener and emitter
  expect(addSpy).toHaveBeenCalledWith('mouseup', expect.any(Function))
  expect(emitterOn).toHaveBeenCalledWith('tokenizeCurrentSentence', expect.any(Function))

  // Calling the registered handler should call selectTokens
  const handler = addSpy.mock.calls[0][1]
  ;(handler as any)('evt')
  expect(fakeThis.selectTokens).toHaveBeenCalledWith('evt')

  // cleanup
  ;(ReviewPage as any).beforeUnmount.call(fakeThis)
})

test('template renders token when eligibleTokens contains TMToken', () => {
  const token = new TMToken(0, 1, 'a', 'Candidate')
  // ensure reviewed=false path (user-inactive) exercised by default
  const store: any = { state: { annotationManager: { inputSentences: [] } } }
  const emitter = { on: vi.fn(), off: vi.fn() }
  const vm = shallowMount(ReviewPage, {
    global: { mocks: { $store: store, emitter }, stubs: ['labels-block', 'token', 'aggregate-block', 'token-block', 'info-bar'] },
    computed: { 
      eligibleTokens: () => [token],
      tokenManager: () => ({ tokens: [token], removeBlock: vi.fn(), isOverlapping: () => null }),
      versionControlManager: () => ({ addUndo: vi.fn() }),
    }
  })
  // token branch should render a token stub
  expect(vm.html()).toContain('token-stub')
})

test('template renders token with reviewed=true shows active class', () => {
  const token = new TMToken(0, 1, 'a', 'Candidate')
  token.reviewed = true
  const store: any = { state: { annotationManager: { inputSentences: [] } } }
  const emitter = { on: vi.fn(), off: vi.fn() }
  const vm = shallowMount(ReviewPage, {
    global: { mocks: { $store: store, emitter }, stubs: ['labels-block', 'token', 'aggregate-block', 'token-block', 'info-bar'] },
    computed: { 
      eligibleTokens: () => [token],
      tokenManager: () => ({ tokens: [token], removeBlock: vi.fn(), isOverlapping: () => null }),
      versionControlManager: () => ({ addUndo: vi.fn() }),
    }
  })
  expect(vm.html()).toContain('user-active')
})

// Test removed - references deleted TMTokenAggregate class

// Test removed - references deleted TMTokenAggregate class

test('template handles unknown token types (no branch matches)', () => {
  const store: any = { state: { annotationManager: { inputSentences: [] } } }
  const emitter = { on: vi.fn(), off: vi.fn() }
  const vm = shallowMount(ReviewPage, {
    global: { mocks: { $store: store, emitter }, stubs: ['labels-block', 'token', 'aggregate-block', 'token-block', 'info-bar'] },
    computed: { 
      eligibleTokens: () => ([{ foo: 'bar' }]),
      tokenManager: () => ({ removeBlock: vi.fn() }),
      versionControlManager: () => ({ addUndo: vi.fn() }),
    }
  })

  // none of the stubs should render because the object isn't an instance of any TMToken classes
  expect(vm.html()).not.toContain('token-stub')
  expect(vm.html()).not.toContain('aggregate-block-stub')
  expect(vm.html()).not.toContain('token-block-stub')
})

test('template renders token-block when eligibleTokens contains TMTokenBlock', async () => {
  const block = new TMTokenBlock(5, 6, [new TMToken(5,6,'x','Candidate')], { id:1, name:'L', color: 'red-11' } as any, 'Candidate')
  const store: any = { state: { annotationManager: { inputSentences: [] } } }
  const emitter = { on: vi.fn(), off: vi.fn() }
  const vm = shallowMount(ReviewPage, {
    global: { mocks: { $store: store, emitter }, stubs: ['labels-block', 'token', 'aggregate-block', 'token-block', 'info-bar'] },
    computed: { 
      eligibleTokens: () => [block],
      tokenManager: () => ({ tokens: [block], removeBlock: vi.fn(), isOverlapping: () => null }),
      versionControlManager: () => ({ addUndo: vi.fn() }),
    }
  })
  expect(vm.html()).toContain('token-block-stub')
  // ensure the @remove-block handler is wired and callable (covers template listener branch)
  const spy = vi.spyOn(vm.vm as any, 'onRemoveBlock')
  // provide the mapped managers expected by onRemoveBlock
  ;(vm.vm as any).versionControlManager = { addUndo: vi.fn() }
  ;(vm.vm as any).tokenManager = { removeBlock: vi.fn() }
  // directly call the handler (emitting on the shallow stub lacks vm in this environment)
  ;(vm.vm as any).onRemoveBlock(block.start)
  expect((vm.vm as any).versionControlManager.addUndo).toHaveBeenCalledWith((vm.vm as any).tokenManager)
  expect((vm.vm as any).tokenManager.removeBlock).toHaveBeenCalledWith(block.start)
  expect(spy).toHaveBeenCalledWith(block.start)
})

test('template renders token-block with reviewed=true shows active class', () => {
  const block = new TMTokenBlock(5, 6, [new TMToken(5,6,'x','Candidate')], { id:1, name:'L', color: 'red-11' } as any, 'Candidate')
  block.reviewed = true
  const store: any = { state: { annotationManager: { inputSentences: [] } } }
  const emitter = { on: vi.fn(), off: vi.fn() }
  const vm = shallowMount(ReviewPage, {
    global: { mocks: { $store: store, emitter }, stubs: ['labels-block', 'token', 'aggregate-block', 'token-block', 'info-bar'] },
    computed: { 
      eligibleTokens: () => [block],
      tokenManager: () => ({ tokens: [block], removeBlock: vi.fn(), isOverlapping: () => null }),
      versionControlManager: () => ({ addUndo: vi.fn() }),
    }
  })
  expect(vm.html()).toContain('user-active')
})

})();

