name: Deployment

on:
    push:
        branches: ["main"]

    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "deployment"
    cancel-in-progress: false

jobs:
  build-tool:
    name: Build AnNER Tool
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.MODIFIED_GITHUB_TOKEN }}
    - name: Install pnpm and dependencies
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 8.5.0
        run_install: false
    - name: Install
      run: pnpm install
    - name: Build
      run: pnpm build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: anner-tool
        path: dist/

  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MODIFIED_GITHUB_TOKEN }}
      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v2
        id: pnpm-install-docs
        with:
          version: 8.5.0
          run_install: false
      - name: Install
        run: pnpm install
      - name: Build Docs
        run: pnpm typedoc
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/
    
  deploy:
    name: Deploy to GitHub branch
    needs: [build-tool, build-docs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MODIFIED_GITHUB_TOKEN }}
          ref: "deployment"
      - name: Download AnNER Artifact
        uses: actions/download-artifact@v4
        with:
          name: anner-tool
      - name: Download Docs Artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs/
      - name: Publish
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Deployment Build - ${{ github.sha }}
          branch: "deployment"
          push_options: '--force'