name: Pull Request Validation

on:
    pull_request:
        branches: ["main"]
        types:
          - opened
          - reopened
          - synchronize
          - closed

concurrency: preview-${{ github.ref }}

permissions:
  pull-requests: write

jobs:
    build-tool:
        name: Build AnNER Tool Preview
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
              token: ${{ secrets.MODIFIED_GITHUB_TOKEN }}
        - name: Install pnpm and dependencies
          uses: pnpm/action-setup@v2
          id: pnpm-install
          if: github.event.action != 'closed'
          with:
              version: 8.5.0
              run_install: false
        - name: Install
          run: pnpm install
          if: github.event.action != 'closed'
        - name: Build
          run: pnpm vite build --base=/AnNER/pr-preview/pr-${{ github.event.number }}/
          if: github.event.action != 'closed'
        - name: Deploy preview
          uses: rossjrw/pr-preview-action@v1
          with:
            source-dir: dist/
            preview-branch: deployment
            token: ${{ secrets.MODIFIED_GITHUB_TOKEN }}