name: Pull Request Validation

on:
    pull_request:
        branches: ["main"]

concurrency: preview-${{ github.ref }}

permissions:
  pull-requests: write

jobs:
    lint:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                token: ${{ secrets.MODIFIED_GITHUB_TOKEN }}
          - name: ESLint Test
            uses: AbdulRehman-1/eslint-action@latest
            with:
              extensions: 'js,jsx,ts,tsx'
              annotations: true

    build-tool:
        name: Build AnNER Tool Preview
        runs-on: ubuntu-latest
        needs: lint
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
              token: ${{ secrets.MODIFIED_GITHUB_TOKEN }}
        - name: Install pnpm and dependencies
          uses: pnpm/action-setup@v2
          id: pnpm-install
          with:
              version: 8.5.0
              run_install: false
        - name: Install
          run: pnpm install
        - name: Build
          run: pnpm build
        - name: Deploy preview
          uses: rossjrw/pr-preview-action@v1
          with:
            source-dir: dist/
            preview-branch: deployment
            token: ${{ secrets.MODIFIED_GITHUB_TOKEN }}